# Generated by Django 4.0.1 on 2022-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('packing', models.TextField(blank=True, null=True)),
                ('places', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
